apiVersion: v1
data:
  drawer: "true"
  form: "true"
  showFormStructure: "true"
  drawerSize: large
kind: ConfigMap
metadata:
  name: template-gcp-alloydb-instance-card
  namespace: gcp-alloydb-system
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: template-gcp-alloydb-instance-card
  namespace: gcp-alloydb-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: template-gcp-alloydb-instance-customform
      namespace: gcp-alloydb-system
      resource: customforms
      verb: GET
  - template:
      apiVersion: core.krateo.io/v1alpha1
      name: gcp-alloydb-instance
      namespace: gcp-alloydb-system
      resource: compositiondefinitions
      verb: DELETE
  app:
    template:
      color: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end }
      content: Provision a Google Cloud Alloydb AlloyDBInstance via Config Connector.
      icon: fa-brands fa-google
      tags: gcp-alloydb-system,0.1.0
      title: gcp-alloydb-instance
      status: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + .status }
      date: ${ .getCompositionDefinition.metadata.creationTimestamp }
  propsRef:
    name: template-gcp-alloydb-instance-card
    namespace: gcp-alloydb-system
  type: card
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/gcp-alloydb-system/compositiondefinitions/gcp-alloydb-instance"
    verb: GET
    headers:
    - 'Accept: application/json'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: template-gcp-alloydb-instance-customform
  namespace: gcp-alloydb-system
data:
  onSubmitId: submit
  onSubmitVerb: POST
  payloadFormKey: spec
  redirectRoute: /compositions/${metadata.namespace}/${metadata.name}
  redirectTimeout: "50"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: template-gcp-alloydb-instance-customform
  namespace: gcp-alloydb-system
spec:
  type: customform
  propsRef:
    name: template-gcp-alloydb-instance-customform
    namespace: gcp-alloydb-system
  actions:
    - template:
        id: submit
        apiVersion: composition.krateo.io/v0-1-0
        verb: POST
        resource: gcpalloydbinstances
        payloadToOverride:
        - name: metadata.namespace
          value: ${ "gcp-alloydb-system" }
  app:
    template:
      schema: ${ .getCRD | .spec.versions[] | select(.name == "v0-1-0") | .schema.openAPIV3Schema.properties.spec }
  api:
  - name: getCRD
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/gcpalloydbinstances.composition.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'
