package main

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"sigs.k8s.io/yaml"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

// blueprintData is the substitution context for the generator's templates.
type blueprintData struct {
	Group        string // storage.cnrm.cloud.google.com
	KccVersion   string // v1beta1
	KccKind      string // StorageBucket
	KccKindLower string // storagebucket
	Service      string // storage
	ServiceTitle string // Storage
	Slug         string // bucket   (Kind with the redundant service prefix stripped)
	ChartName    string // gcp-storage-bucket
	CompKind     string // GcpStorageBucket
	CompPlural   string // gcpstoragebuckets
	CompVersion  string // v0-1-0
	ChartVersion string // 0.1.0
	Namespace    string // gcp-storage-system
	Title        string // GCP Storage StorageBucket
	Stability    string // stable | alpha | beta | unspecified
}

// renderTemplate executes one embedded template (using [[ ]] delimiters) into a file.
func renderTemplate(name, dst string, data blueprintData) error {
	src, err := templatesFS.ReadFile("templates/" + name)
	if err != nil {
		return err
	}
	tmpl, err := template.New(name).Delims("[[", "]]").Parse(string(src))
	if err != nil {
		return fmt.Errorf("parse %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute %s: %w", name, err)
	}
	return os.WriteFile(dst, buf.Bytes(), 0o644)
}

// writeBlueprint materializes a full blueprint directory.
func writeBlueprint(outDir string, data blueprintData, valuesSchema, valuesYAML []byte) error {
	chartDir := filepath.Join(outDir, "chart")
	tplDir := filepath.Join(chartDir, "templates")
	if err := os.MkdirAll(tplDir, 0o755); err != nil {
		return err
	}

	files := []struct{ tmpl, dst string }{
		{"Chart.yaml.tmpl", filepath.Join(chartDir, "Chart.yaml")},
		{"helmignore.tmpl", filepath.Join(chartDir, ".helmignore")},
		{"_helpers.tpl.tmpl", filepath.Join(tplDir, "_helpers.tpl")},
		{"resource.yaml.tmpl", filepath.Join(tplDir, data.Slug+".yaml")},
		{"compositiondefinition.yaml.tmpl", filepath.Join(outDir, "compositiondefinition.yaml")},
		{"customform.yaml.tmpl", filepath.Join(outDir, "customform.yaml")},
		{"blueprint-readme.md.tmpl", filepath.Join(outDir, "README.md")},
	}
	for _, f := range files {
		if err := renderTemplate(f.tmpl, f.dst, data); err != nil {
			return err
		}
	}

	if err := os.WriteFile(filepath.Join(chartDir, "values.schema.json"), valuesSchema, 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(chartDir, "values.yaml"), valuesYAML, 0o644)
}

// marshalSchema emits deterministic, indented JSON for values.schema.json.
func marshalSchema(schema map[string]interface{}) ([]byte, error) {
	b, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// marshalValues turns the minimal-valid values map into commented YAML.
func marshalValues(values map[string]interface{}, data blueprintData) ([]byte, error) {
	body, err := yaml.Marshal(values)
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf(`# Composition spec for %s (generated by tools/kccgen).
#
# Krateo's core-provider builds the Composition CRD from values.schema.json ONLY -- this file is
# not read by core-provider. It carries a minimal, schema-valid set of fields so `+"`helm lint`"+`/
# `+"`helm template`"+` render without overrides; real Compositions supply the full spec.
`, data.ChartName)
	return append([]byte(header), body...), nil
}
